version: '3'
services:
  frontend-dashboard:
    build:
      context: .
      dockerfile: dockerfile.prod
      args:
        - VITE_NODE_ENV=production
        - VITE_SERVER_HOST=http://localhost
        - VITE_SERVER_TEST=TEST-CATALIN-ENV-VARIABLE
    ports:
      - 49202:80