version: '3'
services:
  frontend-dashboard:
    image: frontend-dashboard-dev:latest
    environment:
      VITE_SERVER_HOST: http://localhost
      VITE_SERVER_TEST: TEST-CATALIN-ENV-VARIABLE
    ports:
      - 49201:5173
    volumes:
      - ./src:/app/src