FROM arm64v8/node:18.14-alpine as base
RUN apk update && apk add bash
EXPOSE 3000
ENV NODE_ENV=production
WORKDIR /app
COPY ./package*.json ./
RUN npm config list
RUN npm ci && npm cache clean --force

## Stage 2
FROM base as source
WORKDIR /app
COPY . .

## Stage 3
FROM source as dev
ENV NODE_ENV=development
WORKDIR /app
RUN npm config list
RUN npm install && npm cache clean --force
CMD ["npm", "run", "dev"]

## Stage 4
FROM source as test
ENV NODE_ENV=development
COPY --from=dev WORKDIR /app/node_modules /app/node_modules/
RUN eslint .
RUN npm test

## Stage 5(default, production)
FROM source as prod
USER node
CMD ["node", "./bin/www"]
